defmodule Realworld.Repo.Migrations.UniqueSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:articles, [:slug], name: "articles_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:articles, [:slug], name: "articles_unique_slug_index")
  end
end
