defmodule Realworld.Repo.Migrations.AddFavoriteReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:favorites, "favorites_article_id_fkey")

    drop constraint(:favorites, "favorites_user_id_fkey")

    alter table(:favorites) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "favorites_user_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    alter table(:favorites) do
      modify :article_id,
             references(:articles,
               column: :id,
               prefix: "public",
               name: "favorites_article_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:favorites, "favorites_article_id_fkey")

    alter table(:favorites) do
      modify :article_id,
             references(:articles,
               column: :id,
               prefix: "public",
               name: "favorites_article_id_fkey",
               type: :uuid
             )
    end

    drop constraint(:favorites, "favorites_user_id_fkey")

    alter table(:favorites) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "favorites_user_id_fkey",
               type: :uuid
             )
    end
  end
end