defmodule Realworld.Repo.Migrations.AddDefaultProfileImage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :image, :text, default: "https://api.realworld.io/images/smiley-cyrus.jpeg"
    end
  end

  def down do
    alter table(:users) do
      modify :image, :text, default: nil
    end
  end
end