defmodule Realworld.Repo.Migrations.DefaultProfileImageServedLocally do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @old_image "https://api.realworld.io/images/smiley-cyrus.jpeg"
  @new_image "/images/smiley-cyrus.jpeg"

  def up do
    alter table(:users) do
      modify(:image, :text, default: @new_image)
    end

    # Existing rows carry the old default too — api.realworld.io is gone.
    execute("UPDATE users SET image = '#{@new_image}' WHERE image = '#{@old_image}'")
  end

  def down do
    alter table(:users) do
      modify(:image, :text, default: @old_image)
    end

    execute("UPDATE users SET image = '#{@old_image}' WHERE image = '#{@new_image}'")
  end
end
